# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e8b4371702d51e512fb48276b918319a14a9477a94488eeb42f0477c3e41fc39a097762cdc495380bc2320a317459b622d700ccb1a4ace838d583f546005edd

test:
  secret_key_base: a7663245bfaba26e30cc8970c8813049e8c869fad3e9f8683a8286a3925c4e66f05c01e41033b243b39cd655cd573de118702506c1e9bc525f9c66efdd8d5fc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
